{
    "name": "AMDEC DEMO",
    "category": "Uncategorized",
    "version": "12.0.1.0",
    "author": "TechnoLibre",
    "license": "AGPL-3",
    "website": "https://technolibre.ca",
    "application": True,
    "depends": ["amdec"],
    "data": [
        "data/amdec_grille_detectabilite.xml",
        "data/amdec_grille_severite.xml",
        "data/amdec_grille_occurence.xml",
        "data/amdec_defaillance.xml",
        "data/amdec_period.xml",
        "data/amdec_project.xml",
        "data/amdec_system.xml",
        "data/amdec_composante.xml",
        "data/amdec_inspection.xml",
        "data/amdec_amdec.xml",
        "data/amdec_line.xml",
    ],
    "installable": True,
}
